---
fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
    portage: 'gentoo/portage'
    augeasproviders_core: 'herculesteam/augeasproviders_core'
    augeasproviders_sysctl: 'herculesteam/augeasproviders_sysctl'
    concat: 'puppetlabs/concat'
    firewall: 'puppetlabs/firewall'
    vcsrepo: 'puppetlabs/vcsrepo'
    puppet: 'theforeman/puppet'
