---
nest::package_use:
  # Don't pull in X
  dev-java/icedtea-bin:
    use: '-gtk'

  # For networkmanager[wifi]
  net-wireless/wpa_supplicant:
    use: 'dbus'

  # Don't pull in X
  sys-boot/plymouth:
    use: '-gtk'

  # required by net-print/cups-filters-1.13.5::gentoo[postscript]
  # required by net-print/cups-2.1.4::gentoo
  # required by dev-java/icedtea-bin-3.4.0::gentoo[cups,-multilib]
  # required by virtual/jdk-1.8.0-r3::gentoo
  # required by app-admin/puppetserver-2.7.1::gentoo
  app-text/ghostscript-gpl:
    use: 'cups'
